// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SP001Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
        driver.Dispose();
    }
    [Test]
    public void sP001()
    {
        driver.Navigate().GoToUrl("http://localhost:5173/user-home/productDetail/id?id=VL10K1");
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
        driver.FindElement(By.CssSelector(".thumbnail:nth-child(3)")).Click();
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".thumbnail:nth-child(4)")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".thumbnail:nth-child(5)")).Click();
        Thread.Sleep(3000);

    }
}
