// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SP004Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
        driver.Dispose();
  }
  [Test]
  public void sP004() {
    driver.Navigate().GoToUrl("http://localhost:5173/user-home/productDetail/id?id=VL10K1");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
        Thread.Sleep(6000);

        driver.FindElement(By.CssSelector(".size-container:nth-child(3) > button")).Click();
        Thread.Sleep(6000);
    driver.FindElement(By.CssSelector(".size-container:nth-child(1) > button")).Click();
        Thread.Sleep(6000);

        driver.FindElement(By.CssSelector(".size-container:nth-child(3) > button")).Click();
  }
}
