// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TK04Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
        driver.Dispose();

    }
    [Test]
    public void tK04()
    {
        driver.Navigate().GoToUrl("http://localhost:5173/user-home");
        driver.Manage().Window.Size = new System.Drawing.Size(1300, 816);
        driver.FindElement(By.CssSelector(".search-bar")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".search-bar")).SendKeys("Nhẫn");
        {
            var element = driver.FindElement(By.CssSelector(".search-results"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        Thread.Sleep(3000);

        {
            var element = driver.FindElement(By.CssSelector(".search-results"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        Thread.Sleep(3000);

        {
            var element = driver.FindElement(By.CssSelector(".search-results"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".banner-img")).Click();
        Thread.Sleep(3000);

    }
}
