// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DM003Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
        driver.Dispose();

    }
    [Test]
    public void dM003()
    {
        driver.Navigate().GoToUrl("http://localhost:5173/user-home");
        driver.Manage().Window.Maximize();
        driver.FindElement(By.CssSelector(".product-list:nth-child(2) .product:nth-child(1) .product-image")).Click();
        Thread.Sleep(3000);

        js.ExecuteScript("window.scrollTo(0,0)");
        driver.FindElement(By.CssSelector(".filter-section:nth-child(3) .filter-btn:nth-child(1)")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".search-btn")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".filter-section:nth-child(3) .filter-btn:nth-child(2)")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".search-btn")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".filter-section:nth-child(3) .filter-btn:nth-child(3)")).Click();
        Thread.Sleep(3000);

        driver.FindElement(By.CssSelector(".search-btn")).Click();
        Thread.Sleep(3000);

    }
}
