// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SP05Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
        driver.Dispose();
    }
  [Test]
  public void sP05() {
    driver.Navigate().GoToUrl("http://localhost:5173/user-home");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".product-list:nth-child(2) .product:nth-child(1) .product-image")).Click();
        Thread.Sleep(6000);
        js.ExecuteScript("window.scrollTo(0,0)");
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".product-card:nth-child(2) .product-image")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".add-to-cart > button:nth-child(3)")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".add-to-cart > button:nth-child(3)")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".add-to-cart > button:nth-child(1)")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".add-to-cart > button:nth-child(1)")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector("button:nth-child(3)")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector("button:nth-child(3)")).Click();
  }
}
