// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SP08Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
        driver.Dispose();
    }
  [Test]
  public void sP08() {
    driver.Navigate().GoToUrl("http://localhost:5173/user-home/productDetail/id?id=N14K1");
        Thread.Sleep(6000);
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".tab-button:nth-child(2)")).Click();
        Thread.Sleep(6000);
        js.ExecuteScript("window.scrollTo(0,300)");
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector("textarea")).Click();
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector("textarea")).SendKeys("cÒN MÀU KHÁC KHÔNG");
        Thread.Sleep(6000);
        driver.FindElement(By.CssSelector(".comment-input-container > button")).Click();
        Thread.Sleep(6000);
        Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Bình luận đã được gửi!"));
        Thread.Sleep(6000);
        js.ExecuteScript("window.scrollTo(0,310.3999938964844)");
        Thread.Sleep(6000);
    }
}
